### ISSUE TITLE
gitignor

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#2]
Ко всем проектам нужно обязательно создавать в корневой папке файл .gitignor. Почитай про него и его синтаксис. Его можно создать вручную и заполнить в текстовом редакторе, а можно через git-комманды в gitbash. В этом файле указываются:
- файлы и папки, которые создаёт IDEA (папка .idea, файлы iml)
- файлы и папки, которые создаёт Maven (target, .mvn)
- файлы, содержащие логины-пароли

Для учебных проектов можно просто создать этот файл один раз и копировать во все последующие проекты, меняя название проектов и добавляя постепенно, что будет требоваться

**Comment by kiaev** [comment]
Добавлен файл .gitignore, в качестве примера игнорируются все файлы *.docx. Выполнен Pull Request в основную ветку main

**Comment by AlexanderHantel** [comment]
Нужно добавить туда папки .idea и target со всем содержимым, и файл myArtifact.iml. У того, кто будет клонировать твой проект, такиеи папки создаст Идея или другая среда разработки и Мавен, хранить их в репозитории незачем, это мусор.
