### ISSUE TITLE
Reverse - Reverser, splitter - split

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#3]
https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/main/java/Main.java#L13

1. С точки зрения клиента, пользующегося твоим кодом, он должен по названию твоего метода понимать, что этот метод делает. У тебя метод называется splitter, а клиенту нужно не сплиттить текст, а ревёрсить. Для того, чтобы сплиттить, уже есть стандартный String.split(). Исходя из этой ошибки и сама архитектура класса Reverse страдает. Когда ты поменяешь порядок вызовов методов, архитектура сама выстроится более правильно и логично.
2. По clean code есть правило: Классы это сущности, поэтому они должны называться именами существительными (Reverser, Printer, Builder), не глаголами типа Reverse, Print, Build. А методы, это какие-то действия, соответственно и называться они должны глаголами (reverse, print, build)
3. Если уже существуют стандартные джавовские методы с определённым названием (split, reverse), то надо подумать, делают ли твои методы что-то другое, чем уже существующие. Если ответ утвердительный, то надо назвать свой метод именно так, как он работает, пусть название будет длинным, главное, чтобы по названию было максимально понятно, что делает метод. Если ответ отрицательный, то возможно и не было смысла писать свой метод.

Если нет времени читать книгу по клинкоду, то можешь посмотреть видео Немчинского https://www.youtube.com/watch?v=otrfSgeK3JI

**Comment by kiaev** [comment]
this issue amended
