### ISSUE TITLE
Lines, comments

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#4]
https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/main/java/Reverse.java#L3-L16

Не знаю, это гитхаб добавил после каждой строки лишнюю пустую строку или ты. На случай, если ты - лишние строки мешают читать код, приходится чаще листать страницу туда-сюда. Разделять нужно блоки кода друг от друга, когда они логически как-то различаются. Или если метод состоит из 2-3 строк, то разделять их тоже не следует в большинстве случаев. Всё что внутри блока if-else и так визуально разделено скобками, дополнительно разделять пробелами не нужно, чаще всего.

Писать комментарии к каждому действию тоже не нужно - сам код должен читаться так, чтобы было понятно без комментариев, что происходит. Комментарии чаще всего используются только как документация, либо когда в коде происходит что-то не очень логичное и требует пояснения.

**Comment by kiaev** [comment]
According to issue "Lines, comments #4" amend all classes : Deleted unnecessary comments and spaces
