### ISSUE TITLE
Code slyle

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#5]
https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/main/java/Reverse.java#L22
Знаки математических и логических операций должны обрамляться пробелами: 
int i = 0
i <= words...
words.length - 1

https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/main/java/Reverse.java#L30
Тут лишний пробел после messege. 

И переменную нужно исправить на message, в Идее есть комманда Shift+F6, она переименовывает переменную по всему коду, достаточно только переименовать в том месте, где переменная объявлена.

https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/main/java/Reverse.java#L42
Лучше всё-таки объявлять переменные в разных строках, так её будет проще искать. Идея и сама джава допускает и это, и блоки if-else без фигурных скобок, но на практике это усложняет чтение кода.

**Comment by kiaev** [comment]
According to issue "Code slyle #5" amend class Reverser
