### ISSUE TITLE
StringJoiner 

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#6]
https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/main/java/Reverse.java#L30

Для этого действия есть класс StringJoiner и его метод join. Каждый раз, когда ты пользуешься конкатенацией, под капотом происходит вызов классов StringJoiner, StringBuilder и StringBuffer. Чтобы избежать множественного их создания и вызова, с точки зрения оптимизации лучше пользоваться ими напрямую, а потом результат их работы переводить в строку и возвращать. К тому же после StringJoiner тебе не придётся удалять лишние пробелы.

**Comment by kiaev** [comment]
According to issue "StringJoiner #6" amend class Reverser: used StringJoiner
