### ISSUE TITLE
Tests names

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#7]
https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/test/java/TestUnit.java#L5
Тест-классы, если они тестируют какой-то один класс, должны называться так же как тестируемый класс + "Test": ReverserTest
Так их будет проще искать в большом проекте.

https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/test/java/TestUnit.java#L21
Нормы названий для тест-методов разные в разных компаниях, но примерный шаблон такой:
названиеМетода_долженВозвращатьТоТо_еслиДанныеТакиеТо
названиеМетода_долженВыбрасыватьИсключение_еслиДанныеТакиеТо

в нашем случае:
reverse_ShouldReversWholeWord_ifOneWordAndOnlyCapitalLetters
таким образом, когда ты запускаешь всю пачку тестов, ты видишь какие методы упали и по их названиям понимаешь, что именно сломалось.

**Comment by kiaev** [comment]
according to issue "Test names #7" amend class ReverserTest: names methods
