### ISSUE TITLE
Code style in tests

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#8]
https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/test/java/TestUnit.java#L7-L16
Эти переменные лучше объявлять внутри тестовых методов, потому что когда ты запускаешь пачку тестов, и какие-то падают, ты должен открыть упавший метод, и прямо в нём увидеть, какие данные приходят и какие должны вернуться, а не листать в начало станицы, высматривая значение каждой переменной. Тестовые методы должны восприниматься скорее как отдельные сущности с собственными переменными. 

https://github.com/kiaev/Project1/blob/1a4e44bc9b38b74801f1680593b72700683dbe75/src/test/java/TestUnit.java#L31-L33
Не нужно добавлять печать в консоль после каждого теста, ты и так в Идее будешь видеть, какие методы пошли, какие упали, и с какими данными. Попробуй специально сломать какой-нибудь метод, чтобы увидеть, как идея отображает упавшие методы.

**Comment by kiaev** [comment]
According to issue "Code style in tests #8" in class ReverserTest delete out in console, move variables in methods
