### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by AlexanderHantel** [kiaev/Project1#9]
Нужно добавить в тот метод, который будет основным, в первую строку проверку на null. Если приходит null, нужно выбросить исключение IllegalArgumentException с каким-нибудь сообщением. Смысл в том, что нужно стараться избегать возникновения NullPointerException, оно выбрасывается, когда в какой-то джавовский или другой библиотечный метод приходит null. Также нужно написать тест, проверяющий, что выбрасывается именно IllegalArgumentException, когда приходит null.

**Comment by kiaev** [comment]
According to issue #9 added class checkNull and added testNullPointerException
